use thiserror::Error;

use solana_program::program_error::ProgramError;

#[derive(Error, Debug, Copy, Clone)]
pub enum TroveError {
    /// Invalid instruction
    #[error("Invalid Instruction")]
    InvalidInstruction,
    /// Not Rent Exempt
    #[error("Not Rent Exempt")]
    NotRentExempt,
    /// ExpectedAmountMismatch
    #[error("ExpectedAmountMismatch")]
    ExpectedAmountMismatch,
    /// AmountOverflow
    #[error("AmountOverflow")]
    AmountOverflow,
    /// AmountOverflow
    #[error("AccountParsingError")]
    AccountParsingError,

    /// The owner of the input isn't set to the program address generated by the program.
    #[error("Input account owner is not the program address")]
    InvalidAccountOwner,

    /// Account is not a signer
    #[error("Input account must be a signer")]
    InvalidSigner,

    /// The account cannot be initialized because it is already in use.
    #[error("Account is already initialized")]
    AlreadyInitialized,

    /// Math operation overflow
    #[error("Math operation overflow")]
    MathOverflow,
}

impl From<TroveError> for ProgramError {
    fn from(e: TroveError) -> Self {
        ProgramError::Custom(e as u32)
    }
}
